remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [APCSA home of Java coding]
description: [Learn how to code in Java]
